### ISSUE TITLE
user's openssh.authorizedKeys.keys not creating ~/.ssh/authorized_keys file

### ISSUE THREAD

**Issue by realsnick** [nix-community/nixos-generators#197]
to reproduce :+1: 
the repository is: https://github.com/Sky360-Repository/sky360/

under `nixOS` directory

the user.nix file is at https://github.com/Sky360-Repository/sky360/blob/main/nixOS/Systems/Base/Users/snick.nix

user is created with the initial password but the .ssh/authorized_keys file isn't being created. 

command to build the image (rpi-4): 
```
nix build --option system aarch64 .#fisheye
```

**Comment by Lassulus** [comment]
have you checked /etc/ssh/authorized_keys.d ?

**Comment by realsnick** [comment]
my mistake...misspelled my local ~/.ssh file

just FYI ... nixos puts the authorized key in `/etc/ssh/authorized_keys.d` in a file named by the user

**Comment by realsnick** [comment]
@Lassulus thank you. I noticed there is no /etc/nixos/configuration.nix or hardware-configuration.nix

is there a way to get the hardware-configuration.nix that was used to build the image somehow? nix-generate doesn't seem to create a good one on the rpi4

**Comment by Lassulus** [comment]
nope, there is no easy way. since we generate the image out of the config there is no way to recover the config after the image is generated. you can of course copy the config yourself.

As there are many different ways to setup your config there is no general way to do this. usually I tell people to git clone it in the container/machine
