### ISSUE TITLE
Private Git Repos negatively impacted

### ISSUE THREAD

**Issue by TomMD** [nix-community/nixos-generators#273]
nixos-generators presumably uses a sandbox, meaning even `builtins.fetchGit` can't fetch private git repositories.  For example, I tried:

```
builtins.fetchGit { url = "git@github.com....", rev = ... }
```

And while my host has access, the nixos-generator build errors with (among other text):

```
Host key verification failed.
fatal: Could not read from remote repository.
```

**Comment by Lassulus** [comment]
host key verification failed means that the host is not in the known_hosts of the user where the daemon is connecting from. You can try ssh-ing to github.com as root once and accepting the key

**Comment by Mic92** [comment]
If you have `builtins.fetchGit` in your nix code than this shouldn't be broken by nixos-generators. nixos-generators does not runs builtins.fetchGit inside a sandbox just like any other nix-build tool. The only way this can happen is if you actually run nixos-generators yourself inside a build but than you also wouldn't get `Host key verification failed` because it wasn't able to reach this host. Try to git clone normally from the url that you are trying to fetch. You should be able to see the same error.
